version: '3'

services:
    database:
        image: mariadb:10.7.3
        container_name: sf_database
        restart: unless-stopped
        environment:
            MARIADB_USER: root
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: app
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
        volumes:
            - database-data:/var/lib/mysql:rw
            - ./var:/var/www/var
        labels:
            com.symfony.server.service-prefix: 'DATABASE'

    web:
        image: nginx:alpine
        container_name: sf_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www:delegated
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        user: '${USER_ID}:${GROUP_ID}'
        image: grafikart/php:php8.2-2
        container_name: sf_php
        restart: unless-stopped
        volumes:
            - .:/var/www:delegated
        depends_on:
            - database

    ## Development Tools
    maildev:
        image: mailhog/mailhog
        container_name: sf_maildev
        ports:
            - "1080:8025"
        labels:
            com.symfony.server.service-prefix: 'MAILER'

    adminer:
        image: adminer:4.8.1
        container_name: sf_adminer
        restart: unless-stopped
        depends_on:
            - database
        environment:
            APP_ENV: dev
            ADMINER_DESIGN: pepa-linha
            ADMINER_DEFAULT_SERVER: database
        ports:
            - "8082:8080"

volumes:
    database-data:
        driver:
            local